title: Piusdibus - Das Tagebuch
author:
  name: Christoph Niederhauser v/o Pius
  email: ch.niederhauser@immerda.ch
description: > # this means to ignore newlines until "show_excerpts:"
  Wildes Sammelsurium an Gedanken, Inspirationen und Ideen zu Themen wie Feldbotanik, 
  Musik, Garten und Umwelt. Der Blog ist als Fundgrube zum drin herumwühlen zu verstehen.
  Mir geht's um den bewährten quick-and-dirty-Ansatz: Besser einfach mal ausprobieren
  und schauen wie die Dinge funktionieren.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: "dark_angepasst"

  # generate social links in footer
  social_links:
    twitter: piusdibus
    github:  piusdibus
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: piusdibus
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    mastodon:
      - username: piusdibus
        instance: tooting.ch
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - blog.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
